# Generated by Django 2.1 on 2020-03-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formnew', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='formdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=10)),
                ('Middlename', models.CharField(max_length=10)),
                ('Lastname', models.CharField(max_length=10)),
                ('Event', models.CharField(max_length=10)),
                ('Available_slot', models.IntegerField()),
            ],
        ),
    ]
