# Generated by Django 2.1 on 2020-03-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formnew', '0004_remove_register_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('mail_id', models.CharField(max_length=255)),
                ('phone_no', models.IntegerField()),
                ('Event', models.CharField(max_length=10)),
                ('time_slot', models.CharField(max_length=10)),
            ],
        ),
    ]
