# Generated by Django 2.1 on 2020-03-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formnew', '0005_enroll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enroll',
            old_name='mail_id',
            new_name='Email_id',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='phone_no',
            new_name='Phone_no',
        ),
        migrations.RenameField(
            model_name='enroll',
            old_name='name',
            new_name='full_name',
        ),
    ]
