# Generated by Django 2.1 on 2020-03-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formnew', '0006_auto_20200318_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
