# Generated by Django 2.1 on 2020-03-22 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formnew', '0009_auto_20200322_0940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
